# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac0321a113b8fd99f372c1b4f4cfa1e462fd1c6964867cd7ad3b22eb2008538eabfa3c88e3d591956bf57c8655bf98f0ffb97b5bd93d28b3c8faf788a43760c8

test:
  secret_key_base: 14761c7e9bf583a172bd16127beca2b996f140af72d68f61e5a5ee113d13cc1655e008abfbdafbe2be6535c93968130573f16579d524e2cc624486e681f5716e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
